use Grocery_stored;

# Analysis Question
-- 1. Customer Insights
# -- How many unique customer have place orders?
select count(distinct c.customer_id) as unique_id
from customers c 
join orders o on o.customer_id = c.customer_id;

-- Which Customers have placed the highest number of orders?
select c.customer_name, c.customer_id, count(o.order_id) as total_orders
from customers c
join orders o on o.customer_id = c.customer_id
group by c.customer_name, c.customer_id
order by total_orders desc limit 1;

-- What is the total and average purchase value per customer?
select o.customer_id, c.customer_name, sum(od.total_price) as total_purchase, avg(od.total_price) as average_purchase
from orders o
join customers c on o.customer_id = c.customer_id
join order_details od on o.order_id = od.order_id
group by o.customer_id;

# -- Who are the top 5 customers by total purchase amount?
select o.customer_id, c.customer_name, sum(od.total_price) as total_purchase
from orders o
join customers c on o.customer_id = c.customer_id
join order_details od on o.order_id = od.order_id
group by o.customer_id
order by total_purchase desc limit 5;

-- 2. Product Performance
# -- How many products exist in each category?
select c.category_id, c.category_name, count(p.product_id) as total_product
from products p
join categories c on p.category_id = c.category_id
group by c.category_id;

-- what is the average price of products by category?
select c.category_id, c.category_name, avg(p.price) as average_price
from products p
join categories c on p.category_id = c.category_id
group by c.category_id;

-- Which products have the highest total sales volume (by quantity)?
select p.product_name, sum(od.quantity) as high_sales
from order_details od
join products p  on p.product_id = od.product_id
group by p.product_name
order by high_sales desc limit 1;

# -- What is the total revenue generated by each product?
select p.product_name, sum(od.total_price) as total_revenue
from order_details od
left join products p  on p.product_id = od.product_id
group by p.product_name;

-- How do product sales vary by category and supplier?
select c.category_name, s.supplier_name,sum(od.total_price) as total_sales
from order_details od
inner join products p on od.product_id = p.product_id
inner join categories c on p.category_id = c.category_id
inner join suppliers s on p.supplier_id = s.supplier_id
group by c.category_name, s.supplier_name
order by c.CATEGORY_NAME,total_sales 
DESC;

# 3. Sales and Order Trends
-- How many orders have been placed in total?
select count(*) as total_orders from orders; 

-- What is the average value per order?
select sum(total_price)/count(distinct order_id) as average_value
from order_details;

-- On which dates were the most orders placed?
select order_date, count(order_id) as order_count
from orders
group by order_date
order by order_count desc limit 1;

# -- What are the monthly trends in order volume and revenue?

SELECT 
    DATE_FORMAT(o.order_date,'%Y-%m') AS Month,
    COUNT(DISTINCT o.Order_ID) AS Order_Volume,
    SUM(od.Total_Price) AS Total_Revenue
FROM Orders o
Inner JOIN Order_details od 
    ON o.Order_ID = od.Order_ID
GROUP BY  Month
ORDER BY Month;


-- How do order patrns very across weekdays and weekends ?

select dayname(order_date) as weekday,
monthname(order_date) as month_,
count(order_id) as total_orders 
from orders 
group by weekday,month_
order by weekday,month_;


# 4️. Supplier Contribution
-- How many suppliers are there in the database?
select count(*) as count_suppliers
 from suppliers;

-- Which supplier provides the most products?
select s.supplier_id,s.supplier_name, count(p.product_id) as most_products
from suppliers s
join products p on s.supplier_id = p.supplier_id
group  by s.supplier_id
order by most_products desc limit 1;

-- What is the average price of products from each supplier?
select s.supplier_id ,s.supplier_name, sum(p.price)/count(distinct p.product_id) as average_price
from suppliers s
join products p on s.supplier_id = p.supplier_id
group by s.supplier_id;

# -- Which suppliers contribute the most to total product sales (by revenue)?
select s.supplier_id ,s.supplier_name, sum(od.total_price) as total_product_sales
from suppliers s
join products p on s.supplier_id = p.supplier_id
join order_details od on p.product_id = od.product_id
group by s.supplier_id 
order by total_product_sales desc limit 1;

# 5️. Employee Performance
-- How many employees have processed orders?
select count(distinct employee_id)
from employees;

-- Which employees have handled the most orders?

select e.employee_id,e.employee_name,count(o.order_id) as ordered_most
from employees e
join orders o on e.employee_id = o.employee_id
group by e.employee_id
order by ordered_most desc limit 1;


-- What is the total sales value processed by each employee?
select e.employee_id,e.employee_name, count(od.total_price) as total_sales
from employees e
inner join orders o on e.employee_id = o.employee_id
inner join order_details od on o.order_id = od.order_id
group by e.employee_id
order by total_sales desc;

-- What is the average order value handled per employee?
select e.employee_id, e.employee_name, sum(od.total_price)/count(distinct o.order_id) as average_value
from employees e
inner join orders o on e.employee_id = o.employee_id
inner join order_details od on o.order_id = od.order_id
group by e.employee_id
order by average_value desc;

# 6️. Order Details Deep Dive
-- What is the relationship between quantity ordered and total price?

select quantity, avg(total_price) as average_total_price,count(*) as order_count
from order_details
group by quantity
order by quantity;


-- What is the average quantity ordered per product?
select od.product_id, p.product_name,sum(od.quantity)/count(distinct od.ord_detID) as average_quantity
from order_details od
join products p on od.product_id = p.product_id
group by od.product_id
order by average_quantity;

-- How does the unit price vary across products and orders?
select od.product_id,p.product_name,od.each_price,count(od.order_id) as times_ordered
from order_details od
join products p on od.product_id = p.product_id
group by od.product_id,od.each_price;



